version: "2"
services:
    www:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./shop:/var/www/html/
        links:
            - db
        networks: 
            - default
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: prestashop
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - presistent:/var/lib/mysql
        networks:
            - default
volumes:
    presistent:
